CREATE TABLE IF NOT EXISTS "echo_message" (
	"id"	INTEGER NOT NULL,
	"version"	INTEGER NOT NULL,
	"created"	INTEGER NOT NULL,
	"modified"	INTEGER NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "echo_learn" (
	"id"	INTEGER NOT NULL,
	"version"	INTEGER NOT NULL,
	"created"	INTEGER NOT NULL,
	"modified"	INTEGER NOT NULL,
	"user"	INTEGER NOT NULL,
	"learning"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "echo_data" (
	"id"	INTEGER NOT NULL,
	"version"	INTEGER NOT NULL,
	"created"	INTEGER NOT NULL,
	"modified"	INTEGER NOT NULL,
	"key"	TEXT NOT NULL UNIQUE,
	"value"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);